name: Deploy to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.drnet.co.ke
          username: deploy@drnet.co.ke
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: /home/drnetcok/app/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
            .github/**

      - name: Install dependencies and restart app
        uses: appleboy/ssh-action@master
        with:
          host: drnet.co.ke
          username: drnetcok
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 21098
          script: |
            source /home/drnetcok/nodevenv/app/22/bin/activate
            cd /home/drnetcok/app
            npm install --production
            touch /home/drnetcok/app/tmp/restart.txt
            echo "âœ” Dependencies installed and app restarted!"
